services:
    frontend:
        build:
            context: ./frontend
            dockerfile: dockerfile
        ports:
            - 3000:80
    backend:
        build:
            context: ./backend
            dockerfile: dockerfile
        ports:
            - "5000:5000"
        env_file:
            - ./backend/.env
networks:
    app_network:
        driver: bridge
