# syntax=docker/dockerfile:1

FROM python:3.11.10

WORKDIR /python-docker

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

RUN apt-get update && \
    apt-get install -y ffmpeg

COPY . .

ENV FLASK_APP=main.py

EXPOSE 5000

CMD [ "flask", "run", "--host=0.0.0.0"]